const CACHE_TIME = 86400000
const GITHUB_CACHE = 'GITHUB_CACHE'
const GHOST_CACHE = 'GHOST_CACHE'

module.exports = {
  CACHE_TIME: CACHE_TIME,
  GHOST_CACHE: GHOST_CACHE,
  GITHUB_CACHE: GITHUB_CACHE
}
